# Default path ~/.swoosh-resources/PLA_Application_Name/app.ini
# Symlink to ~/.swoosh-config.d/PLA_Application_Name
[APP:PLA_Application_Name]
title=Application
subtitle=Name
platform=pla
category=Action-adventure
info=~/.swoosh-resources/PLA_Application_Name/info.html
cover=~/.swoosh-resources/PLA_Application_Name/cover.webp
soundtrack=~/.swoosh-resources/PLA_Application_Name/soundtrack.mp3
run_default=command-to-run ~/.swoosh-resources/PLA_Application_Name/rom.pla
kill_default=command-to-kill "command-to-run"
run_config=command-to-configure "command-to-run"


